import puppeteer from "puppeteer-core";
import { mkdirSync } from "node:fs";
const OUT = new URL("../art-shots/v19/", import.meta.url).pathname;
mkdirSync(OUT, { recursive: true });
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const browser = await puppeteer.launch({ executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", headless: "new", args: ["--no-first-run", "--mute-audio"] });
const page = await browser.newPage();
await page.setViewport({ width: 390, height: 844, deviceScaleFactor: 2 });
const errs = []; page.on("pageerror", (e) => errs.push(e.message)); page.on("console", (m) => { if (m.type() === "error") errs.push("[c]" + m.text()); });
await page.goto("http://localhost:5199/?dev=1", { waitUntil: "networkidle0" });
await page.evaluate(() => localStorage.removeItem("tiny-harbor-save"));
await page.reload({ waitUntil: "networkidle0" });
await page.waitForFunction(() => !!window.TH);
await page.evaluate(() => { window.TH.state.discovered = ["sardina","boqueron","caballa","dorada","lubina","pulpo","delfin","reysol","aurora"]; window.TH.state.zonesUnlocked = 4; });
await page.tap("#tabbar [data-tab='mapa']");
await sleep(500);
await page.screenshot({ path: `${OUT}movil-pescadoteca.png` });
if (errs.length) { console.error("ERR", errs); process.exit(1); }
console.log("✓ pescadoteca");
await browser.close();
